### ISSUE TITLE
大佬在 掘金上跟着你的这个教程学习 想请教下几个功能实现

### ISSUE THREAD

**Issue by Yakumo-Yukari** [punkisnotdead3/go_web_app#1]
1，用户等级功能，在用户发帖 回帖 增加经验来升级  那么 等级数据库要怎么设计呢

2，想实现发帖添加封面功能，可以添加网络图片或者上传 在没有使用网络图片或者没有上传的时候就使用默认图片

可以在后面的课程讲下吗？

**Comment by punkisnotdead3** [comment]
可以 我后面补一下 这2个功能，但是你要等一段时间了，这段时间有点忙。。

**Comment by punkisnotdead3** [comment]
> 1，用户等级功能，在用户发帖 回帖 增加经验来升级 那么 等级数据库要怎么设计呢
> 
> 2，想实现发帖添加封面功能，可以添加网络图片或者上传 在没有使用网络图片或者没有上传的时候就使用默认图片
> 
> 可以在后面的课程讲下吗？

我也是服务端新人，并不是服务端大佬啊。这几个功能 后面我可以补一下，但是要等一段时间

**Comment by Yakumo-Yukari** [comment]
> > 1，用户等级功能，在用户发帖 回帖 增加经验来升级 那么 等级数据库要怎么设计呢
> > 2，想实现发帖添加封面功能，可以添加网络图片或者上传 在没有使用网络图片或者没有上传的时候就使用默认图片
> > 可以在后面的课程讲下吗？
> 
> 我也是服务端新人，并不是服务端大佬啊。这几个功能 后面我可以补一下，但是要等一段时间

好的  谢谢了
